[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn api.translate:app --host 0.0.0.0 --port $PORT --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"
HF_TOKEN = "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"
TRANSFORMERS_CACHE = "/app/.cache"
HF_HOME = "/app/.cache"